package org.sandboxpowered.api.entity;

import org.sandboxpowered.api.registry.Registry;
import org.sandboxpowered.api.util.Identity;

public class EntityTypes {
    public static final Registry.Entry<Entity.Type> AREA_EFFECT_CLOUD = get("area_effect_cloud");
    public static final Registry.Entry<Entity.Type> ARMOR_STAND = get("armor_stand");
    public static final Registry.Entry<Entity.Type> ARROW = get("arrow");
    public static final Registry.Entry<Entity.Type> BAT = get("bat");
    public static final Registry.Entry<Entity.Type> BEE = get("bee");
    public static final Registry.Entry<Entity.Type> BLAZE = get("blaze");
    public static final Registry.Entry<Entity.Type> BOAT = get("boat");
    public static final Registry.Entry<Entity.Type> CAT = get("cat");
    public static final Registry.Entry<Entity.Type> CAVE_SPIDER = get("cave_spider");
    public static final Registry.Entry<Entity.Type> CHICKEN = get("chicken");
    public static final Registry.Entry<Entity.Type> COD = get("cod");
    public static final Registry.Entry<Entity.Type> COW = get("cow");
    public static final Registry.Entry<Entity.Type> CREEPER = get("creeper");
    public static final Registry.Entry<Entity.Type> DONKEY = get("donkey");
    public static final Registry.Entry<Entity.Type> DOLPHIN = get("dolphin");
    public static final Registry.Entry<Entity.Type> DRAGON_FIREBALL = get("dragon_fireball");
    public static final Registry.Entry<Entity.Type> DROWNED = get("drowned");
    public static final Registry.Entry<Entity.Type> ELDER_GUARDIAN = get("elder_guardian");
    public static final Registry.Entry<Entity.Type> END_CRYSTAL = get("end_crystal");
    public static final Registry.Entry<Entity.Type> ENDER_DRAGON = get("ender_dragon");
    public static final Registry.Entry<Entity.Type> ENDERMAN = get("enderman");
    public static final Registry.Entry<Entity.Type> ENDERMITE = get("endermite");
    public static final Registry.Entry<Entity.Type> EVOKER_FANGS = get("evoker_fangs");
    public static final Registry.Entry<Entity.Type> EVOKER = get("evoker");
    public static final Registry.Entry<Entity.Type> EXPERIENCE_ORB = get("experience_orb");
    public static final Registry.Entry<Entity.Type> EYE_OF_ENDER = get("eye_of_ender");
    public static final Registry.Entry<Entity.Type> FALLING_BLOCK = get("falling_block");
    public static final Registry.Entry<Entity.Type> FIREWORK_ROCKET = get("firework_rocket");
    public static final Registry.Entry<Entity.Type> FOX = get("fox");
    public static final Registry.Entry<Entity.Type> GHAST = get("ghast");
    public static final Registry.Entry<Entity.Type> GIANT = get("giant");
    public static final Registry.Entry<Entity.Type> GUARDIAN = get("guardian");
    public static final Registry.Entry<Entity.Type> HORSE = get("horse");
    public static final Registry.Entry<Entity.Type> HUSK = get("husk");
    public static final Registry.Entry<Entity.Type> ILLUSIONER = get("illusioner");
    public static final Registry.Entry<Entity.Type> ITEM = get("item");
    public static final Registry.Entry<Entity.Type> ITEM_FRAME = get("item_frame");
    public static final Registry.Entry<Entity.Type> FIREBALL = get("fireball");
    public static final Registry.Entry<Entity.Type> LEASH_KNOT = get("leash_knot");
    public static final Registry.Entry<Entity.Type> LLAMA = get("llama");
    public static final Registry.Entry<Entity.Type> LLAMA_SPIT = get("llama_spit");
    public static final Registry.Entry<Entity.Type> MAGMA_CUBE = get("magma_cube");
    public static final Registry.Entry<Entity.Type> MINECART = get("minecart");
    public static final Registry.Entry<Entity.Type> CHEST_MINECART = get("chest_minecart");
    public static final Registry.Entry<Entity.Type> COMMAND_BLOCK_MINECART = get("command_block_minecart");
    public static final Registry.Entry<Entity.Type> FURNACE_MINECART = get("furnace_minecart");
    public static final Registry.Entry<Entity.Type> HOPPER_MINECART = get("hopper_minecart");
    public static final Registry.Entry<Entity.Type> SPAWNER_MINECART = get("spawner_minecart");
    public static final Registry.Entry<Entity.Type> TNT_MINECART = get("tnt_minecart");
    public static final Registry.Entry<Entity.Type> MULE = get("mule");
    public static final Registry.Entry<Entity.Type> MOOSHROOM = get("mooshroom");
    public static final Registry.Entry<Entity.Type> OCELOT = get("ocelot");
    public static final Registry.Entry<Entity.Type> PAINTING = get("painting");
    public static final Registry.Entry<Entity.Type> PANDA = get("panda");
    public static final Registry.Entry<Entity.Type> PARROT = get("parrot");
    public static final Registry.Entry<Entity.Type> PIG = get("pig");
    public static final Registry.Entry<Entity.Type> PUFFERFISH = get("pufferfish");
    public static final Registry.Entry<Entity.Type> ZOMBIE_PIGMAN = get("zombie_pigman");
    public static final Registry.Entry<Entity.Type> POLAR_BEAR = get("polar_bear");
    public static final Registry.Entry<Entity.Type> TNT = get("tnt");
    public static final Registry.Entry<Entity.Type> RABBIT = get("rabbit");
    public static final Registry.Entry<Entity.Type> SALMON = get("salmon");
    public static final Registry.Entry<Entity.Type> SHEEP = get("sheep");
    public static final Registry.Entry<Entity.Type> SHULKER = get("shulker");
    public static final Registry.Entry<Entity.Type> SHULKER_BULLET = get("shulker_bullet");
    public static final Registry.Entry<Entity.Type> SILVERFISH = get("silverfish");
    public static final Registry.Entry<Entity.Type> SKELETON = get("skeleton");
    public static final Registry.Entry<Entity.Type> SKELETON_HORSE = get("skeleton_horse");
    public static final Registry.Entry<Entity.Type> SLIME = get("slime");
    public static final Registry.Entry<Entity.Type> SMALL_FIREBALL = get("small_fireball");
    public static final Registry.Entry<Entity.Type> SNOW_GOLEM = get("snow_golem");
    public static final Registry.Entry<Entity.Type> SNOWBALL = get("snowball");
    public static final Registry.Entry<Entity.Type> SPECTRAL_ARROW = get("spectral_arrow");
    public static final Registry.Entry<Entity.Type> SPIDER = get("spider");
    public static final Registry.Entry<Entity.Type> SQUID = get("squid");
    public static final Registry.Entry<Entity.Type> STRAY = get("stray");
    public static final Registry.Entry<Entity.Type> TRADER_LLAMA = get("trader_llama");
    public static final Registry.Entry<Entity.Type> TROPICAL_FISH = get("tropical_fish");
    public static final Registry.Entry<Entity.Type> TURTLE = get("turtle");
    public static final Registry.Entry<Entity.Type> EGG = get("egg");
    public static final Registry.Entry<Entity.Type> ENDER_PEARL = get("ender_pearl");
    public static final Registry.Entry<Entity.Type> EXPERIENCE_BOTTLE = get("experience_bottle");
    public static final Registry.Entry<Entity.Type> POTION = get("potion");
    public static final Registry.Entry<Entity.Type> TRIDENT = get("trident");
    public static final Registry.Entry<Entity.Type> VEX = get("vex");
    public static final Registry.Entry<Entity.Type> VILLAGER = get("villager");
    public static final Registry.Entry<Entity.Type> IRON_GOLEM = get("iron_golem");
    public static final Registry.Entry<Entity.Type> VINDICATOR = get("vindicator");
    public static final Registry.Entry<Entity.Type> PILLAGER = get("pillager");
    public static final Registry.Entry<Entity.Type> WANDERING_TRADER = get("wandering_trader");
    public static final Registry.Entry<Entity.Type> WITCH = get("witch");
    public static final Registry.Entry<Entity.Type> WITHER = get("wither");
    public static final Registry.Entry<Entity.Type> WITHER_SKELETON = get("wither_skeleton");
    public static final Registry.Entry<Entity.Type> WITHER_SKULL = get("wither_skull");
    public static final Registry.Entry<Entity.Type> WOLF = get("wolf");
    public static final Registry.Entry<Entity.Type> ZOMBIE = get("zombie");
    public static final Registry.Entry<Entity.Type> ZOMBIE_HORSE = get("zombie_horse");
    public static final Registry.Entry<Entity.Type> ZOMBIE_VILLAGER = get("zombie_villager");
    public static final Registry.Entry<Entity.Type> PHANTOM = get("phantom");
    public static final Registry.Entry<Entity.Type> RAVAGER = get("ravager");
    public static final Registry.Entry<Entity.Type> LIGHTNING_BOLT = get("lightning_bolt");
    public static final Registry.Entry<Entity.Type> PLAYER = get("player");
    public static final Registry.Entry<Entity.Type> FISHING_BOBBER = get("fishing_bobber");

    private static Registry.Entry<Entity.Type> get(String type) {
        return Entity.Type.REGISTRY.get(Identity.of("minecraft", type));
    }
}